name: Build and test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

env:
  PYTKET_RUN_REMOTE_TESTS: 1
  PYTKET_REMOTE_AZURE_RESOURCE_ID: ${{ secrets.PYTKET_REMOTE_AZURE_RESOURCE_ID }}
  PYTKET_REMOTE_AZURE_LOCATION: ${{ secrets.PYTKET_REMOTE_AZURE_LOCATION }}
  PYTKET_REMOTE_AZURE_STORAGE: ${{ secrets.PYTKET_REMOTE_AZURE_STORAGE }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  checks:
    name: Build and test module
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build and test
      shell: bash
      run: ./.github/workflows/build-test nomypy
