name: Build and test

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Build and test module
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        pyver: ['3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python
      if: github.event_name == 'push' || github.event_name == 'schedule'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyver }}
    - name: Build and test
      if: github.event_name == 'push' || github.event_name == 'schedule'
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
