name: Build and test

on:
  pull_request:
    branches:
      - main
  schedule:
    # 04:00 every Tuesday morning
    - cron: '0 4 * * 2'
  workflow_dispatch: {}

jobs:
  checks:
    name: Build and test module
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
        submodules: true
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build and test
      shell: bash
      env:
        PYTKET_RUN_REMOTE_TESTS: 1
        AZURE_QUANTUM_CONNECTION_STRING: ${{ secrets.AZURE_QUANTUM_CONNECTION_STRING }}
      run: ./.github/workflows/build-test mypy
    - name: install poetry
      run: pip install poetry
    - name: Install docs dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd docs
        bash ./install.sh
        for w in `find wheelhouse/ -type f -name "*.whl"` ; do poetry install $w ; done
    - name: Build docs
      if: matrix.os == 'ubuntu-latest'
      timeout-minutes: 20
      run: |
        cd docs
        poetry run bash ./build-docs.sh
