name: Build and test

on:
  pull_request:
    branches:
      - main
  schedule:
    # 04:00 every Tuesday morning
    - cron: '0 4 * * 2'
  workflow_dispatch: {}

jobs:
  checks:
    name: Build and test module
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build and test
      shell: bash
      env:
        PYTKET_RUN_REMOTE_TESTS: 1
        AZURE_QUANTUM_CONNECTION_STRING: ${{ secrets.AZURE_QUANTUM_CONNECTION_STRING }}
      run: ./.github/workflows/build-test mypy
    - name: Install docs dependencies
      run: pip install -r .github/workflows/docs/requirements.txt
    - name: Build docs
      timeout-minutes: 20
      run: ./.github/workflows/docs/check-build-docs
